# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611c9142edc659910dcc272d762afe7f7334d89b86540ce4bebe8001d8277e0c58488f39cafb004ecbd64afdc6d1a0ed6b7aee4f12bddd754d64ed4a008924dd

test:
  secret_key_base: ee1dc954dd05c3df9ef56aa236432dddd14e963189fc579968147f1cf4792f5583d6289a342d6622135f8fde5b21f0b004cac2e074d694de7df4983e284e6312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
